languageCode = "en-us"
title = "Analytics Dream"
baseurl = ""
relativeURLs = true
canonifyURLs = false
uglyurls = true
theme = "hugo_theme_robust"
[Params]
  Author = "Andrew Sears"
  disqusShortname = "analyticsdream"
  description = "Analytics Dream"
  Subtitle = "Blogging about clouds, lakes, streams and analytics"


